# Site settings
title: About me
description: Homepage for information about myself
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andrew Samuels
user_description: My name is Andrew Samuels and I am a Senior at Clemson University studying Computer Science. In addition to my major I am also minoring in Modern Languages: Japanese. I am particularly interested in the Cyber Security field, and am actively involved in Clemson's Cyber Security Club as the club's Secretary.
user_title: Clemson Student
email: absamue@g.clemson.edu
github_username:  absamue

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
