# Site settings
title: Andrew Samuels
description: Andrew Samuels: What does he know?? Does he know things?? Let's find out!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andrew Samuels
user_title: Aspiring Software Developer
user_description: I am currently a Senior at Clemson University studying Computer Science, and in addition to my major I am also minoring in Japanese for fun. As of now, I am actively searching for a Software Development position in the Raleigh-Durham NC area. I am particularly interested in the Cyber Security field, and am actively involved in Clemson's Cyber Security Club as the club's Secretary.
github_username:  absamue
email: absamue@g.clemson.edu

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
